unbalancedparens/legacy

client/app/assets/js/app.extra.js, client/app/assets/scss/_header.scss, client/app/homepage/homepage.html, client/app/index.html
Add effect to menu when scrolling
=> style: add fx to menu

client/app/app.js, client/app/assets/scss/_barber-profile.scss, client/app/assets/scss/_style-detail.scss, client/app/assets/scss/app.scss, client/app/barbers/profile.html, client/app/hair_styles/detail.html, client/app/index.html
basic templates for barber and hair stye detail views
=> feat: add barber profile and style detail view templates

client/app/rating.js
Fix grunt uglify task, remove html commented lines into rating.js
=> fix ratings / grunt uglify issue

client/app/assets/scss/_header.scss
=> style: add logo effect

client/app/app.js, client/app/services/services.js
Add factory to set and get barbers and style id
=> dev: add factory for barbers and styles

notes.js, package.json, server/config/braintree.js, server/config/middleware.js, server/config/twilio.js, server/config/venmo.js, server/server.js
feat: add notes and partial implementation for Twilio and Venmo; add notes, routing, and implementation for Braintree
=> feat: notes, Twilio, Venmo, Braintree

client/app/barbers/barberProfileController.js, server/barbers/barbersController.js, server/barbers/barbersRoutes.js, server/config/middleware.js, server/server.js
Fetch data in barber profile page
=> feat: fetch barber data in profile

client/app/barbers/barber-list/barber-list.html, client/app/barbers/barber-list/barber-list.js, client/app/services/services.js
pass profile id from list view to make available to detial view
=> feat: pass profile id to factory function

client/app/assets/scss/_list-page.scss, client/app/assets/scss/_previous.scss, client/app/assets/scss/app.scss, client/app/barbers/barber-list/barber-list.html
=> feat: add barber info to list page

client/app/barbers/barber-list/barber-list.html, client/app/rating.js
Rating feature is done, waiting for views to be finished to fully complete. Average rating is rendering on barbers listing. Have set aside actual rating of the service for when the view is finished.
=> feat: completed rating feature

client/app/assets/scss/_profile-page.scss, client/app/barbers/barber-profile.html, client/app/barbers/barberProfileController.js, client/app/index.html
Barber page styling
Added add to cart for barber and style
Used local storage to store the order
=> feat: profile page sendding order data in local storage, style added

client/app/assets/scss/_profile-page.scss
=> fix: profile page style name

client/app/assets/scss/_header.scss, client/app/assets/scss/_list-page.scss, client/app/assets/scss/_profile-page.scss, client/app/assets/scss/_variables.scss, client/app/assets/scss/app.scss, client/app/barbers/barber-list/barber-list.html
Styling on the barber list page, name and ratings optimization
=> style: list-page

client/app/assets/scss/_list-page.scss, client/app/assets/scss/_profile-page.scss, client/app/barbers/barber-profile.html, client/app/barbers/barberProfileController.js, client/app/hairstyles/hairstyle-list/hairstyle-list.html, client/app/hairstyles/hairstyle-list/hairstyle-list.js
Add modal with bigger style picture on style list page and profile page
=> feat: add big style picture and links into list and profile page

client/app/barbers/barber-profile.html
fix for the profile page magnifier
=> fix: magnifier profile page

client/app/about-us/about.html, client/app/app.js, client/app/assets/scss/_about-us.scss, client/app/assets/scss/_footer.scss, client/app/assets/scss/_home.scss, client/app/assets/scss/_list-page.scss, client/app/assets/scss/_profile-page.scss, client/app/assets/scss/app.scss, client/app/barber-registration/barber-registration.html, client/app/barber-registration/barber-registration.js, client/app/homepage/homepage.html, client/app/index.html
Homepage modification
Footer creation with style and links
About us modification
Barber registration page created
Profile page style selection modified
=> feat: homepage WIP, about us page, barbers page

client/app/assets/scss/_list-page.scss, client/app/barbers/barber-list/barber-list.html
add hairstyle search box to filter list of barbers
=> hairstyle filter

client/app/auth/auth.js, client/app/index.html, client/app/order/order.html, client/app/order/order.js, client/app/services/services.js, server/config/braintree.js, server/config/middleware.js, server/config/nodemailer.js, server/config/stripe.js, server/config/twilio.js, server/config/venmo.js
feat: re-implement email functionality
refactor: refactor hacky jQuery email implementation
style: code cleanup
=> feat: email functionality, code cleanup

client/app/app.js, client/app/assets/scss/_header.scss, client/app/barbers/barberProfileController.js, client/app/index.html, client/app/order/order.js, client/app/services/header.js
Added cart information into the header
=> Header menu cart

client/app/assets/scss/_order.scss, client/app/assets/scss/app.scss, client/app/order/order.html
=> style: order-page styling
